[formatting]
align_comments = false
indent_string = "    "

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "workspace.dependencies", "workspace.lints.clippy"]

[rule.formatting]
reorder_keys = true
