[package]
name = "snowcap"
version = "0.0.1"
edition = "2021"

[dependencies]
smithay-client-toolkit = "0.19.1"
anyhow = { workspace = true }
iced = { version = "0.12.1", default-features = false, features = ["wgpu", "tokio"] }
iced_wgpu = "0.12.1"
iced_runtime = "0.12.1"
iced_futures = "0.12.0"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
raw-window-handle = "0.6.2"
xdg = { workspace = true }
smithay-clipboard = "0.7.1"
tokio = { workspace = true }
tokio-stream = { workspace = true }
futures = "0.3.30"
prost = { workspace = true }
tonic = { workspace = true }
tonic-reflection = { workspace = true }
snowcap-api-defs = { workspace = true }
xkbcommon = { workspace = true }

[lints]
workspace = true
