[package]
name = "pinnacle-config"
version = "0.2.0-alpha.1"
edition = "2024"

[dependencies]
pinnacle-api = { git = "http://github.com/pinnacle-comp/pinnacle", default-features = false }

[features]
default = ["snowcap"]
snowcap = ["pinnacle-api/snowcap"]
